<?php
/**
 *@file
 *AJAX support for the kasahorow Toolkit. This is a JSON version of menu.inc
 */

/**
 *@ingroup hook_menu
 *Define a base path that reinteprets every path in order to return a
 *JSON equivalent
 */
function kajax_menu() {
  $items = array();
  $items['js'] = array(
    'page callback' => '_kjson_menu',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['jsviewer'] = array(
    'page callback' => '_kjson_view',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['jsmessages'] = array(
    'page callback' => '_kjson_messages',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  $items['admin/kw/settings/ajax'] = array(
    'page callback' => '_kajax_admin',
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK
  );
  return $items;
}


function kajax_kwapi(&$kasa, $op, $a3 = NULL, $a4 = NULL){
  $output = '';
  switch($op){
    case 'admin':
      $output = array(array(t('Ajax'),
                  'For developer clients',
                  'Settings'));
    break;
  }
  return $output;
}
/**
 *Use the menu-path to return just the body of a page as a json
 *object without the blocks, etc
 */
function _kjson_menu() {
  $args = func_get_args();
  $path = join('/', $args);
  if(!sizeof($args)) {//This is the front page
    $path = drupal_get_normal_path(variable_get('site_frontpage', 'node'));
  }
  drupal_json(menu_execute_active_handler($path));
}

function _kjson_view() {
  //Also add it here since URLs with a # don't reload
  drupal_add_js(drupal_get_path('module', 'kajax').'/kajax.js');
  $path = url(drupal_get_path('module', 'kclient'));
  $msg = t('Loading...');
  return "<div id='kjson'><img src='$path/ajax-loader.gif' />$msg</div>";
}

function _kjson_messages(){
  drupal_json(theme('status_messages'));
}

function _kajax_admin(){
  $form = array();
  $form['kajax_excluded_elements'] = array(
    '#title' => t('Excluded HTML tags'),
    '#type' => 'textarea',
    '#default_value' => variable_get('kajax_excluded_elements', 'form'),
  );
  return system_settings_form($form);
}