<?php
// $Id:
	/**
	 * Implementation of hook_help
	 */
	function moneybookers_help( $path, $arg ) {
		switch ($path) {
    		case 'admin/help#reportbug':
      			$output = '<p>'.t('The moneybookers module enables payment to be made moneybookers.com ' .
      					'via the drupal platform.').'</p>';	
      					
      		return $output;
      	}
	}
	
	/**
	 * Implementation of hook_perm
	 */
	function moneybookers_perm() {
		return array('access moneybookers');	
	}
	
	/**
	 * Implementation of hook_menu
	 */
	function moneybookers_menu() {
		$items['moneybookers'] = array(
    		'title' => t('Donate'),
    		'page callback' => 'reportbug_site_page',
    		'access arguments' => array('access moneybookers'),
    		'type' => MENU_SUGGESTED_ITEM,
    		'file' => 'moneybookers.pages.inc',
  		);
  		return $items;	
	}

?>
